name=LumPixel
version=1.0.0
author=LumHalo <lumhalo@rakura.fr>
maintainer=LumHalo <lumhalo@rakura.fr>
sentence=Gestion ruban LED pour LumHalo
paragraph=Permet un contrôle précis des rubans LED RGB, RGBW ou autres en utilisant le périphérique RMT de l'ESP32.
category=Display
url=https://github.com/LumHalo/LumPixel
architectures=esp32
depends=
