name=LumaPixel
version=1.0.0
author=Luma Light <luma.light@rakura.fr>
maintainer=Luma Light <luma.light@rakura.fr>
sentence=Gestion ruban LED pour Luma Light
paragraph=Permet un contrôle précis des rubans LED SK6812 RGBW ou autres en utilisant le périphérique RMT de l'ESP32 avec conversion automatique RGB vers RGBW.
category=Display
url=https://github.com/Luma-Lights/LumaPixel
architectures=esp32
depends=
